schema_version = 3

[[source]]
name = "aemo-isp-2024"
local_path = "sources/aemo/2024-integrated-system-plan.pdf"
public_url = "https://www.aemo.com.au/-/media/files/major-publications/isp/2024/2024-integrated-system-plan-isp.pdf?la=en"

[source.metadata]
publisher = "Australian Energy Market Operator"

[[source]]
name = "aemo-isp-2026"
local_path = "sources/aemo/2026-integrated-system-plan.pdf"
public_url = "https://www.aemo.com.au/-/media/files/major-publications/isp/2026/2026-integrated-system-plan-isp.pdf?rev=7f5dfd18aa1b4a3aab704c424f75afd3&sc_lang=en"

[source.metadata]
publisher = "Australian Energy Market Operator"
