"""Render inspectable Markdown from the canonical table model."""

from __future__ import annotations

import re

from ._text import escape_markdown_inline
from .models import NormalisedTable


_START = "<!-- tracecite-embedding:start"
_END = "<!-- tracecite-embedding:end -->"


def render_embedding_block(table: NormalisedTable) -> str:
    """Render a visible, collapsible Quarto/Pandoc inspection block."""

    title = table.caption or (
        table.section_path[-1] if table.section_path else table.table_id
    )
    lines = [
        f'{_START} table-id="{table.table_id}" source-hash="{table.source_hash}" -->',
        '::: {.callout-note collapse="true" title="TraceCite embedding representation"}',
        "",
        f"**Table:** {escape_markdown_inline(title)}  ",
        f"**Table identifier:** `{table.table_id}`  ",
        f"**Normaliser:** `{table.normaliser_version}`  ",
    ]
    if table.section_path:
        lines.append(
            "**Section:** "
            + " &gt; ".join(escape_markdown_inline(item) for item in table.section_path)
            + "  "
        )
    if table.source_code_path:
        lines.append(f"**Executable source:** `{table.source_code_path}`  ")
    if table.normalised_text:
        lines.extend(["", *_code_block(table.normalised_text, "text")])
    else:
        lines.extend(
            [
                "",
                "No retrieval text was emitted because this table could not be normalised safely.",
            ]
        )

    if table.diagnostics:
        lines.extend(["", "**Diagnostics**"])
        for item in table.diagnostics:
            location = ""
            if item.row is not None:
                location += f" row {item.row}"
            if item.column is not None:
                location += f" column {item.column}"
            lines.append(
                f"- `{item.severity}:{item.code}`{location}: "
                f"{escape_markdown_inline(item.message)}"
            )

    lines.extend(["", ":::", _END])
    return "\n".join(lines)


def render_debug_markdown(table: NormalisedTable) -> str:
    """Render raw, canonical, and retrieval representations for one table."""

    lines = [
        "# TraceCite table-normalisation inspection",
        "",
        f"Source document: `{table.document_path}`  ",
        f"Table identifier: `{table.table_id}`",
        "",
        "## Raw source",
        "",
        *_code_block(table.raw_source.rstrip(), "markdown"),
        "",
        "## Canonical Markdown",
        "",
        *_code_block(table.canonical_markdown.rstrip(), "markdown"),
        "",
        "## Normalised retrieval text",
        "",
        *_code_block(table.normalised_text, "text"),
        "",
        "## Row records",
        "",
    ]
    for index, (row_id, record) in enumerate(
        zip(table.row_ids, table.row_records, strict=True),
        start=1,
    ):
        lines.extend([f"### Row {index}", "", f"Record ID: `{row_id}`", "", record, ""])
    return "\n".join(lines)


def strip_embedding_blocks(markdown: str) -> str:
    """Remove blocks previously generated by :func:`render_embedding_block`."""

    lines = markdown.splitlines()
    output: list[str] = []
    skipping = False
    for line in lines:
        if line.startswith(_START):
            skipping = True
            while output and not output[-1].strip():
                output.pop()
            continue
        if skipping and line.strip() == _END:
            skipping = False
            continue
        if not skipping:
            output.append(line)
    result = "\n".join(output)
    if markdown.endswith("\n"):
        result += "\n"
    return result


def _code_block(text: str, language: str = "") -> list[str]:
    longest_backticks = max((len(item) for item in re.findall(r"`+", text)), default=0)
    longest_tildes = max((len(item) for item in re.findall(r"~+", text)), default=0)
    if longest_backticks <= longest_tildes:
        marker = "`"
        length = max(3, longest_backticks + 1)
    else:
        marker = "~"
        length = max(3, longest_tildes + 1)
    fence = marker * length
    return [f"{fence}{language}", text, fence]
